version: "3.8"

services:
  angular-portfolio:
    image: node:18
    container_name: angular-portfolio
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "80:4200"
    command: >
      bash -c "npm install -g @angular/cli &&
               npm install &&
               ng serve --host 0.0.0.0 --port 4200"
